config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :description, :price_per_night, :number_of_guests, :address, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :number_of_guests, :address, :price_per_night, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
<h1> All our Flats (<%=@flats.size%>)</h1>

<div class="d-flex">

<%@flats.each do |flat|%>

  <div class="card m-2 shadow-sm bg-body rounded" style="width: 18rem;">
    <div class="card-body bg-light">
      <h5 class="card-title"><%=flat.name%></h5>
      <p class="card-text"><%=flat.address%></p>
    </div>
    <div class="d-flex align-items-top bg-light p-3">
      <i class="fa-solid fa-person mx-1"></i> <p><%=flat.number_of_guests%></p>
      <i class="fa-solid fa-sack-dollar mx-1"></i> <p><%=flat.price_per_night%></p>
    </div>
    <div class= "bg-white p-2">
        <a href=<%=flat_path(flat)%> class="btn btn-primary">More Info</a>
    </div>

  </div>
<% end %>
</div>
</div>

app/views/flats/new.html.erb
<div class="container">
<h1>Add a new flat</h1>
  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <ul class="navbar-nav">
        <li class="nav-item">
          <h3><a class="nav-link" href=<%=flats_path%>>Simple Airbnb</a></h3>
        </li>
      </ul>
      <div class="nav-item">
          <a class="btn btn-primary" href=<%=new_flat_path%>>New flat</a>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>